{
 "title": "Process Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_cpu_seconds_total,instance)"
    }
   },
   {
    "name": "cmdline",
    "query": {
     "query": "label_values(process_cpu_seconds_total{instance=\"$instance\"},cmdline)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"$instance\", cmdline=~\"$cmdline\"}[3m])) by (pid, cmdline, mode)",
     "legendFormat": "pid: {{pid}} {{cmdline}} - {{mode}}"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"$instance\", cmdline=~\"$cmdline\"}[3m])) by (pid, cmdline)",
     "legendFormat": "pid: {{pid}} {{cmdline}} - total"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_rss_bytes{instance=\"$instance\", cmdline=~\"$cmdline\"}",
     "legendFormat": "pid:{{pid}} {{cmdline}} - rss"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(process_io_read_count{instance=\"$instance\", cmdline=~\"$cmdline\"}[5m])",
     "legendFormat": "pid: {{pid}} {{cmdline}} - read iops"
    },
    {
     "expr": "rate(process_io_write_count{instance=\"$instance\", cmdline=~\"$cmdline\"}[5m])",
     "legendFormat": "pid: {{pid}} {{cmdline}} - write iops"
    }
   ]
  },
  {
   "title": "Read/Write bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(process_io_read_bytes{instance=\"$instance\", cmdline=~\"$cmdline\"}[5m])",
     "legendFormat": "pid: {{pid}} {{cmdline}} - read bytes"
    },
    {
     "expr": "rate(process_io_write_bytes{instance=\"$instance\", cmdline=~\"$cmdline\"}[5m])",
     "legendFormat": "pid: {{pid}} {{cmdline}} - write bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_threads_count{instance=\"$instance\", cmdline=~\"$cmdline\"}",
     "legendFormat": "pid: {{pid}} {{cmdline}}"
    }
   ]
  },
  {
   "title": "FDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "process_fds_count{instance=\"$instance\", cmdline=~\"$cmdline\"}",
     "legendFormat": "pid: {{pid}} {{cmdline}}"
    }
   ]
  },
  {
   "title": "ContextSwitch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(process_ctx_switch_voluntary_count{instance=\"$instance\", cmdline=~\"$cmdline\"}[5m])",
     "legendFormat": "pid: {{pid}} {{cmdline}} - voluntary ctx"
    },
    {
     "expr": "rate(process_ctx_switch_involuntary_count{instance=\"$instance\", cmdline=~\"$cmdline\"}[5m])",
     "legendFormat": "pid: {{pid}} {{cmdline}} - involuntary ctx"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "process_network_connections{instance=\"$instance\", cmdline=~\"$cmdline\"}",
     "legendFormat": "pid: {{pid}} - connections"
    }
   ]
  },
  {
   "title": "Process Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "process_total_count{instance=\"$instance\"}",
     "legendFormat": "total process"
    }
   ]
  }
 ]
}